name: Discourse Backup Sync
version: "0.1.2"
slug: discourse_backup_sync
description: Automated backup sync for Discourse forums with intelligent retention (daily, weekly, monthly)
url: https://github.com/jptrsn/ha-discourse-backup-sync
image: ghcr.io/jptrsn/discourse-backup-sync-{arch}
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
hassio_api: true
hassio_role: default
options:
  log_level: "info"
schema:
  log_level: list(debug|info|warning|error)
map:
  - config:rw
  - backup:rw
  - share:rw
  - ssl:ro
panel_icon: mdi:backup-restore
panel_title: Discourse Backup Sync
ingress: true
ingress_port: 8099
